---
title: Noms
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: miamollie@gmail.com
description: Recipe Blog
baseurl: ''
url: http://yourdomain.com
github_username: miamollie
markdown: kramdown
exclude:
- node_modules
